
server:
  port: 8081

spring:
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 10000ms
    lettuce:
      pool:
        #????? ??8
        max-active: 8
        #????????
        max-wait: 1000ms
        #?????????8
        max-idle: 200
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  main:
    allow-circular-references: true
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/selclass?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 1535926365
    hikari:
      pool-name: DateHikariCP
      minimum-idle: 5
      #?????????????10??
      idle-timeout: 1800000
      #????????10
      maximum-pool-size: 10
      #?????????????
      auto-commit: true
      #?????????0?????????1800000?30???
      max-lifetime: 1800000
      #?????????30000?30??
      connection-timeout: 3000
      #?????????????
      connection-test-query: SELECT 1


  #RabbitMQ
  rabbitmq:
    #???
    host: 127.0.0.1
    #???
    username: guest
    #??
    password: guest
    #????
    virtual-host: /
    #??
    port: 5672
    listener:
      simple:
        #???????
        concurrency: 10
        #???????
        max-concurrency: 10
        #???????????????????????????
        prefetch: 1
        #?????????
        auto-startup: true
        #??????????
        default-requeue-rejected: true
    template:
      retry:
        #???????false
        enabled: true
        #???????1000ms
        initial-interval: 1000ms
        #?????????3?
        max-attempts: 3
        #????????
        max-interval: 10000ms
        #???????????2?0  ???10s ????20s ????40s
        multiplier: 1
  web:
    resources:
      add-mappings: true
      cache:
        cachecontrol:
          max-age: 3600
      chain:
        #?????????????
        cache: true
        #??????????
        enabled: true
        #???????gzip?brotil????????
        compressed: true
        #??h5?????????

      static-locations: classpath:/static/
  data:



#mybatis-plus
mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  type-aliases-package: com.fkczxt.selclass

logging:
  level:
    com.fkczxt.selclass.mapper: debug

jwt:
  # Jwt存储的请求头
  tokenHeader: Authorization
  # Jwt加密秘钥
  secret: yeb-secret
  # Jwt 的超期限时间（60*60）*24
  expiration: 604800
  # Jwt负载中拿到开头
  tokenHead: Bearer